### ISSUE TITLE
<CR> script-mapping causes neovim freeze

### ISSUE THREAD

**Issue by jackpeters667** [hrsh7th/nvim-cmp#17] opened 2021-08-12 15:42 UTC
If I include the mapping option on nvim, nvim freezes when I press the Return key (to create a new line)

Removing mapping completely from `setup` allows it to work again.

**Comment by hrsh7th** [comment] 2021-08-12 16:01
@jackpeters667 What do you set a mapping to <CR>?

**Comment by jackpeters667** [comment] 2021-08-12 17:16
It's a clean install with the default mappings you provided in README.md
I tried removing them all and enabling one by one. But the freeze still happens. Just having this causes it to freeze:
```
mapping = {
}
```
Whereas if I remove mapping field completely, then it works.

**Comment by jackpeters667** [comment] 2021-08-14 08:24
All's working now all of a sudden. I'll be watching it and I'll reopen with more info if I come across it again

**Comment by wgxh-cli** [comment] 2021-08-14 13:19
Me too

**Comment by wgxh-cli** [comment] 2021-08-14 13:22
When i remove the `<CR>` mapping's arguments, the plugin was worked. Neovim does not freeze

**Comment by wgxh-cli** [comment] 2021-08-14 13:24
Why the plugin make neovim freeze?

**Comment by hrsh7th** [comment] 2021-08-14 15:06
still no information. I can't reproduce.

**Comment by hrsh7th** [comment] 2021-08-14 17:12
Please reproduce steps for this.

**Comment by ccshao** [comment] 2021-08-15 12:50
Faced the same issue here, and I think it might be related to the `<CR>` mapping. After removing it, `nvim-cmp` doesn't freeze neovim  any more when pressing `Enter`.

Once freezed, ESC not working anymore, but surprisingly <Ctrl-C> works to return to normal model. I could continue to edit, but once pressing `<CR>`, nvim freezes again.

I am using neovim 0.5.0 on macosx 11.4, all plugins are in the latest version. Let me know what other information I need to provide.

Thanks for checking it!

Here is my init.vim setting, with `<CR>` mapping
```
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-path'

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require'cmp'
cmp.setup {
  mapping = {
    ['<C-p>'] = cmp.mapping.prev_item(),
    ['<C-n>'] = cmp.mapping.next_item(),
    ['<C-d>'] = cmp.mapping.scroll(-4),
    ['<C-f>'] = cmp.mapping.scroll(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    })
  },

  -- You should specify your *installed* sources.
  sources = {
      { name = 'buffer' },
      { name = 'nvim_lsp' },
  },
}
EOF
```

**Comment by hrsh7th** [comment] 2021-08-15 13:37
I've tested with the following config. But still can't reproduce... Hm...

I will test it with nvim 0.5.0.

```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-path'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require'cmp'
cmp.setup {
  mapping = {
    ['<C-p>'] = cmp.mapping.prev_item(),
    ['<C-n>'] = cmp.mapping.next_item(),
    ['<C-d>'] = cmp.mapping.scroll(-4),
    ['<C-f>'] = cmp.mapping.scroll(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    })
  },

  -- You should specify your *installed* sources.
  sources = {
      { name = 'buffer' },
      { name = 'nvim_lsp' },
  },
}
EOF
```

**Comment by hrsh7th** [comment] 2021-08-15 13:50
Hm.... I've downgraded neovim to 0.5.0 and using the above configuration but still can't repdoruce...

**Comment by ccshao** [comment] 2021-08-15 14:59
Do you think if it is helpful to post my full init.vim?  I guess there might be some conflicts among plugins, or my setting.

**Comment by rhcher** [comment] 2021-08-15 15:05
> Do you think if it is helpful to post my full init.vim? I guess there might be some conflicts among plugins, or my setting.

I suspect that the problem is related to autopairs.

**Comment by ccshao** [comment] 2021-08-15 15:20
Exactly! Removed `jiangmiao/auto-pairs` solved the freezing issue.

**Comment by rhcher** [comment] 2021-08-15 15:28
> Exactly! Removed `jiangmiao/auto-pairs` solved the freezing issue.

Maybe you should just remove all your customize about CR

**Comment by hrsh7th** [comment] 2021-08-15 15:35
I want to support autopairs like plugins *automatically*.
Thank you! I will investigate it.

**Comment by hrsh7th** [comment] 2021-08-15 15:37
Reproduced!

**Comment by hrsh7th** [comment] 2021-08-15 15:51
I think it fixed by latest commit. Could you test with latest nvim-cmp?

**Comment by ccshao** [comment] 2021-08-15 16:42
Works nicely with `auto-pairs`, thanks! @hrsh7th @rhcher

**Comment by johnallen3d** [comment] 2021-09-01 01:37
> Exactly! Removed jiangmiao/auto-pairs solved the freezing issue.

For what it's worth the opposite now seems to be true for me. I don't typically use auto-pair plugins. When I setup `nvim-cmp` with a mapping for `<CR>` I had the problems described above (freezing, only `<C-c>` works). I then tried installing  `jiangmiao/auto-pairs` as a trouble-shooting step and my `<CR>` mapping now works as expected. Is the usage of an auto-pair plugin expected/required?

**Comment by hrsh7th** [comment] 2021-09-01 03:49
@johnallen3d No. nvim-cmp should work without any pairwise plugins.
If you met the freeze, Could you provide minimal setup?

**Comment by johnallen3d** [comment] 2021-09-01 12:37
OK, thanks for the quick response.

With the following setup I experience the "freeze" behavior.

* I've uninstalled `jiangmiao/auto-pairs `
* Updated to the latest version of `hrsh7th/nvim-cmp`
* Created the most minimal config (below)
* Launched with that config (e.g. `nvim -u ~/.config/nvim/init-basic.lua scratch.txt`)

```lua
-- init-basic.lua
vim.cmd [[packadd packer.nvim]]

require('packer').startup(function()
  use { 'hrsh7th/nvim-cmp' }
end)

local cmp = require'cmp'

cmp.setup {
  mapping = {
    ['<CR>'] = cmp.mapping.confirm()
  },
}
```

**Comment by hrsh7th** [comment] 2021-09-01 12:42
I can't reproduce with this.
```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require'cmp'

cmp.setup {
  mapping = {
    ['<CR>'] = cmp.mapping.confirm()
  },
}
EOF
```

**Comment by johnallen3d** [comment] 2021-09-01 13:59
Yeah, with that configuration I'm not experiencing the freeze. 🤔 When I did my "minimal config" I didn't point it at an alternative location for plugins. Perhaps one of my other plugins is causing the conflict. I'll try to narrow that down.

**Comment by brandoncc** [comment] 2021-09-01 18:17
Thank you all for this thread!

I found that I have the same freezing issue with https://github.com/tpope/vim-endwise

I'm going to open an issue on that repo asking if there is a recommended way to resolve it. If anyone has a fix for it here, I'd love to hear it!

Thanks again.

**Comment by seeM** [comment] 2021-09-05 07:29
@hrsh7th: I have the same issue as @brandoncc. I'm able to reproduce it with:

```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'tpope/vim-endwise'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require'cmp'

cmp.setup {
  mapping = {
    ['<CR>'] = cmp.mapping.confirm()
  },
}
EOF
```

**Comment by 0xA537FD** [comment] 2021-09-07 07:01
I'm facing the same issue and Ctrl + C allows me to return into normal mode otherwise nvim is completely dead. I'm using nvim-cmp with the lsp and luasnip plugin.

```vim
Plugin 'hrsh7th/nvim-cmp'
Plugin 'hrsh7th/cmp-buffer'
Plugin 'hrsh7th/cmp-nvim-lsp'
Plugin 'saadparwaiz1/cmp_luasnip'
```

Together with the config that is provided in the nvim lsp wiki:

```lua
local luasnip = require 'luasnip'

-- nvim-cmp setup
local cmp = require 'cmp'
cmp.setup {
  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body)
    end,
  },
  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    },
    ['<Tab>'] = function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n')
      elseif luasnip.expand_or_jumpable() then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-expand-or-jump', true, true, true), '')
      else
        fallback()
      end
    end,
    ['<S-Tab>'] = function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-p>', true, true, true), 'n')
      elseif luasnip.jumpable(-1) then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-jump-prev', true, true, true), '')
      else
        fallback()
      end
    end,
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'luasnip' },
  },
}
```

Nvim version (nightly): `NVIM v0.6.0-dev+218-g3f526feeb`

**Comment by hrsh7th** [comment] 2021-09-07 07:06
Thank you guys. I get the reproduce the infinite loop. I will fix it later.

**Comment by hrsh7th** [comment] 2021-09-07 07:28
Hm... I'm investigating it. I think vim-endwise define broken mapping...

```lua
{
  buffer = 0,
  expr = 0,
  lhs = "<CR>",
  lnum = 134,
  mode = "i",
  noremap = 0,
  nowait = 0,
  rhs = "<CR><Plug>DiscretionaryEnd",
  script = 0,
  sid = 16,
  silent = 0
}```

The above mapping is automatically defined by vim-endwise.
But it's mapped to `<CR>` and feed `<CR>` with remap instruction... (it will cause infinite loop).

**Comment by hrsh7th** [comment] 2021-09-07 07:49
`imap <CR> <CR>` does not cause the infinite loop. (Maybe it is a vim's internal feature.)

**Comment by 0xA537FD** [comment] 2021-09-07 08:49
I think this might be caused by a configuration error. After further experimentation and some config tweaks I don't face this error anymore. Before that I encountered it every few seconds which made vim completely unusable.

I removed the following things from my lsp config:

```
_G.tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t '<C-n>'
  elseif luasnip.expand_or_jumpable() then
    return t '<Plug>luasnip-expand-or-jump'
  elseif check_back_space() then
    return t '<Tab>'
  end
end

_G.s_tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t '<C-p>'
  elseif luasnip.jumpable(-1) then
    return t '<Plug>luasnip-jump-prev'
  else
    return t '<S-Tab>'
  end
end


-- Map tab to the above tab complete functions
vim.api.nvim_set_keymap("i", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("i", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})
```

Might be possible that it's completely unrelated but for some reason it worked for me and the auto-completion works just like before including LuaSnip.

**Comment by johnallen3d** [comment] 2021-09-07 13:27
I can confirm that removing `vim-endwise` resolves the issue for me.

**Comment by johnallen3d** [comment] 2021-09-07 15:25
Rather than waiting on changes to `vim-endwise` I'm trying out "windwp/nvim-autopairs" which has endwise like rules.

https://github.com/windwp/nvim-autopairs/wiki/Endwise#endwise-experiment

**Comment by hrsh7th** [comment] 2021-09-07 15:26
This is nvim-cmp's issue to me.

**Comment by jackpeters667** [comment] 2021-09-07 18:57
I can confirm this worked for me too.

**Comment by jackpeters667** [comment] 2021-09-07 18:59
> Exactly! Removed `jiangmiao/auto-pairs` solved the freezing issue.

Yesss this was the problem for me as well. I just checked my config and I see I don't have it.

**Comment by hrsh7th** [comment] 2021-09-08 10:25
I've fixed it.

**Closed by hrsh7th** 2021-09-08 10:25 UTC
Labels: bug, reproduced
