### ISSUE TITLE
Can't select any completion item because `snippet engine is not configured`

### ISSUE THREAD

**Issue by hood** [hrsh7th/nvim-cmp#373] opened 2021-10-18 21:16 UTC
Getting the following error whenever I press <CR> to pick a completion item:
<a href="https://imgur.com/qeumdla.png">
  <img src="https://imgur.com/qeumdla.png" />
</a>

Here's my cmp configuration stuff:
```lua
  require'lspconfig'.tsserver.setup{ 
    on_attach = custom_on_attach,
    capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
  }

  -- Setup nvim-cmp.
  local cmp = require'cmp'

  cmp.setup({
    snippet = {},
    mapping = {
      ['<C-d>'] = cmp.mapping.scroll_docs(-4),
      ['<C-f>'] = cmp.mapping.scroll_docs(4),
      ['<C-Space>'] = cmp.mapping.complete(),
      ['<C-e>'] = cmp.mapping.close(),
      ['<CR>'] = cmp.mapping.confirm({ select = true }),
    },
    sources = {
      { name = 'nvim_lsp' },
      { name = 'buffer' },
    }
  })
```

I'm on NeoVim `v0.6.0-dev+479-g9086938f7`

## Update:
I've updated my config's `snippet` section to be like:
```
    snippet = { expand = function() end },
```

and now, whenever I select an item, the word i'm trying to complete gets deleted.
I also found that this happens only for certain types of completion (e.g.: `.toUpperCase` after a string in javascript)
`

**Comment by gabrielbdsantos** [comment] 2021-10-18 22:12
It seems like a duplicate of #304.

You need a snippet engine. If you don't want to use one, there is an alternative [here](https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#no-snippet-plugin).

**Comment by hrsh7th** [comment] 2021-10-20 06:11
For example, html/css/json language server does not support any completion if snippet capabilities wasn't set.

We should define the behavior when receiving `snippet` completion item without a snippet engine.

**Comment by hrsh7th** [comment] 2021-11-02 03:22
The documentation has been updated by the colaborator.

**Closed by hrsh7th** 2021-11-02 03:22 UTC

**Comment by hjanuschka** [comment] 2023-02-17 08:21
for future self:

```
capabilities.textDocument.completion.completionItem.snippetSupport = false
```

turns it of on lsp level
