### ISSUE TITLE
Hang after enter is pressed when langmap option is used

### ISSUE THREAD

**Issue by columbarius** [hrsh7th/nvim-cmp#496] opened 2021-11-09 00:39 UTC
**Describe the bug**

Vim hangs indefinetly when `enter` is pressed in `insert-mode` when the config contains the option `langmap` .

OS: Arch Linux
Neovim: Version 0.5.1

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

lua << EOF
local opt = vim.o
opt.langmap = "yh"
EOF
```

**To Reproduce**

1. Add any `langmap` option to the nvim config
2. Open a document
3. Test that in normal mode with the config above 'y' will moves the cursor to the left like 'h'
4. Go into insert mode
5. Press enter

**Expected behavior**

New line inserted into document

**Additional context**

**Comment by hrsh7th** [comment] 2021-11-09 02:57
I can't reproduce the bug with your configuration.


https://user-images.githubusercontent.com/629908/140853650-92f9a205-1162-4172-b2c5-bee98f899f4e.mp4

**Comment by columbarius** [comment] 2021-11-10 23:01
I noticed i can reproduce the same hang when some closing bracket is suggested and i hit enter without adding sth. in before
```
} else {|}
```
| being the cursor position.

Would you please be so kind to hint me to documentation how to log sth. more useful, since the effect is a stucked editor and the cpu ramping up to full load on a thread.

**Comment by hrsh7th** [comment] 2021-11-13 10:53
I can't reproduce it. Please minimal reproducible configuration and steps.

**Comment by columbarius** [comment] 2021-11-16 02:30
https://user-images.githubusercontent.com/29916710/141884724-dc56be40-0d93-4243-a649-73584b2f710b.mp4

I'm using the configuration as above. At the line in the video I use 'A' to go into insert mode at the end of the line and press enter/new line. The result is nvim not being responsive and cpu usage rising to 100%.

**Comment by columbarius** [comment] 2021-11-16 02:33
Since you can' reproduce it i would like to present more information. Since I don't have any experience with neovim and lua, do you know anything i could try to debug this further?

**Comment by hrsh7th** [comment] 2021-11-16 03:49
Thank you for your response. (I try to reopen if there is a response. sorry.)

Your video seems to be the correct reproduction step to me.

OK. I will test with nvim0.5.x

**Comment by hrsh7th** [comment] 2021-11-16 04:17
```
hrsh7th$ nvim --version
NVIM v0.5.2-dev+20-g1e1fd71fe
Build type: Release
LuaJIT 2.1.0-beta3```

I can't reproduce with the above config and nvim v0.5.2...

**Comment by hrsh7th** [comment] 2021-11-16 04:19
Sorry. To be honest, I have no idea about this problem.
It's very weird...

Hm... I'm using Mac OS X and iTerm2.

**Comment by hrsh7th** [comment] 2021-11-16 04:20
I can't reproduce too with Terminal.app

**Comment by hrsh7th** [comment] 2021-11-16 04:21
Hm... Is the remaining difference the tmux?

**Comment by columbarius** [comment] 2021-11-16 09:47
I tested it with alacritty and with gnome-terminal. Same result.

**Comment by hrsh7th** [comment] 2021-11-23 12:13
Probably not, but can you see if it can be reproduced by the latest nvim-cmp?

_google translated_

**Comment by columbarius** [comment] 2021-12-06 23:31
I found the problem: My plugin folder was not cleaned and nvim-cmp together with https://github.com/jiangmiao/auto-pairs caused this issue. Pressing enter results in an infinite loop trying to evaluate:
```
<Plug>(cmp.utils.keymap.evacuate:<Plug>(...<Plug>(cmp.utils.keymap.evacuate:<Plug>)...))
```
Removing the auto-pairs plugin solved the issue.

Feel free to close the issue. Sry for wasting your time.
I added an updated (this time hopefully complete) minimal config if you want to further investigate it:
```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'jiangmiao/auto-pairs'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF

lua << EOF
local opt = vim.o
opt.langmap = "yh"
EOF
```

**Comment by hrsh7th** [comment] 2021-12-14 15:27
Sorry. I lost this comment with flood notifications.
I'll check it.

**Comment by leonnardo** [comment] 2021-12-27 04:48
I'm having similar issue, but with `nvim-autopairs`
If I have a non empty `langmap` and a loaded `nvim-autopairs` I'm getting a lot of these `<Plug>(cmp.utils.keymap.evacuate:<Plug>(...<Plug>(cmp.utils.keymap.evacuate:<Plug>)...))` 😢

**Comment by leonnardo** [comment] 2022-01-07 16:16
Still not able to reproduce this bug? Can I help debugging this @hrsh7th?
I have no experience developing lua plugins, but with some guidance I can reproduce and fix this bug

**Comment by hrsh7th** [comment] 2022-01-10 17:31
Fixed in https://github.com/hrsh7th/nvim-cmp/pull/720

@leonnardo Could you test with latest main?

**Closed by hrsh7th** 2022-01-10 17:31 UTC
Labels: can't reproduce

**Comment by leonnardo** [comment] 2022-01-11 10:57
> Fixed in #720
> 
> @leonnardo Could you test with latest main?

It worked, thanks!

**Comment by columbarius** [comment] 2022-01-12 08:11
Works for me too. Thanks a lot!

**Comment by DCsunset** [comment] 2022-01-16 00:55
Hello, it seems that pressing Enter in the insert mode now will cause the string `<Plug>(cmp.u.k.evacuate:12)` to be inserted instead of a new line.

I only add `set langmap=aA` to the minimal config `vimrc.vim` and the above problem occurs.

**Comment by hrsh7th** [comment] 2022-01-16 04:13
It seems to be a separated bug. I thinks `langmap=aA` is broken but `langmap=yh` is works fine.

**Comment by DCsunset** [comment] 2022-01-16 04:23
Oh, you're right. Should I open a new issue for this?

**Comment by hrsh7th** [comment] 2022-01-18 14:30
I am confused.
It doesn't reproduce in my environment and doesn't provide any more information than "problem" occur.
We already know that it doesn't work with `set langmap=aA`. Does it mean that there is a problem with other conditions?

**Comment by leonnardo** [comment] 2022-01-18 18:35
Sorry for my silly comment.
I'm using langmap for colemak layout, so with `vim.opt.langmap = "il,li,IL,LI,je,JE,ek,EK,kn,KN,nj,NJ"` I'm getting this `<Plug>(cmp.u.k.fallback:25)`

**Comment by felixkreuk** [comment] 2022-01-23 15:31
@leonnardo I confirm I am having the same issue. Please let me know if I can provide any details that can help.
