### ISSUE TITLE
Error when entering '['

### ISSUE THREAD

**Issue by uga-rosa** [hrsh7th/nvim-cmp#26] opened 2021-08-15 23:07 UTC
`Error executing vim.schedule lua callback: ...kai/.local/share/nvim/plugged/nvim-cmp/lua/cmp/entry.lua:58: index out of range`
The line number is off (originally 56) because I'm inserting lines for debugging purposes.

It does not happen with '{' or '('.
I'm not sure of the exact conditions, but I'll post them in a moment.

```diff
diff --git a/lua/cmp/entry.lua b/lua/cmp/entry.lua
index 73535c6..24db1be 100644
--- a/lua/cmp/entry.lua
+++ b/lua/cmp/entry.lua
@@ -53,6 +53,8 @@ entry.get_offset = function(self)
     if misc.safe(self.completion_item.textEdit) then
       local range = misc.safe(self.completion_item.textEdit.insert) or misc.safe(self.completion_item.textEdit.range)
       if range then
+        print(self.context.cursor_line)
+        print(range.start.character)
         local c = vim.str_byteindex(self.context.cursor_line, range.start.character) + 1
         for idx = c, self.source_offset do
           if not char.is_white(string.byte(self.context.cursor_line, idx)) then
```
![render1629068252893](https://user-images.githubusercontent.com/82267684/129495223-3677e2bd-5eab-42bb-9664-150b19a95800.gif)

**Comment by hrsh7th** [comment] 2021-08-16 02:30
Hm... It's definitely possible bugs. But I can't reproduce it. Needs more investigation.

**Comment by hrsh7th** [comment] 2021-08-16 05:02
I think it should be fixed by latest nvim-cmp. Could you test with it?

**Closed** 2021-08-16 05:02 UTC
Labels: bug, fixable, can't reproduce

**Comment by uga-rosa** [comment] 2021-08-16 06:52
It's fixed!
Thank you for solving an obscure issue.
