### ISSUE TITLE
When the grammar is wrong, some characters will be repeated

### ISSUE THREAD

**Issue by New-arkssac** [hrsh7th/nvim-cmp#1367] opened 2022-12-23 03:10 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Announcement

- [X] I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).

### Minimal reproducible full config

https://github.com/New-arkssac/New-arkssacVimrc/blob/main/lua/lib/cmp.lua

### Description

When I enter a character, the same character will appear at the beginning

### Steps to reproduce

OS: arch linux 6.0.12-zen1-1-zen
nvim: neovim 0.8.1
cmp commit number: 8868cf9a09e5f3c2612a22ccb82dcc6d9f0d0d35

https://user-images.githubusercontent.com/70094380/209262563-eb2ceb6b-df3b-4568-ad1c-b53b17947e5d.mp4

### Expected behavior

No other weird characters appear when I type

### Actual behavior

Other strange characters appear when I enter characters

**Comment by hrsh7th** [comment] 2022-12-27 04:38
I can't reproduce. Please updated nvim-cmp to the latest and re-test again.

You didn't fill the default issue template. I can't understand how to reproduce this. closing.

**Closed by hrsh7th** 2022-12-27 04:38 UTC
Labels: bug
