### ISSUE TITLE
Multiline input with `set cmdheight > 1`

### ISSUE THREAD

**Issue by monkoose** [hrsh7th/nvim-cmp#903] opened 2022-04-14 10:20 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+1425-gff726cc56

### Minimal reproducible full config

Just load nvim-cmp without any config and any completion sources.

### Description

Multiline input in the command line shows only the current line when `set cmdheight=2` or greater.

### Steps to reproduce

- Open neovim
- `set cmdheight=2`
- write in commandline some multiline input something like
```vim
for i in range(4)
  echo 'hello'
endfor
```

### Expected behavior

Do not remove/redraw! or i'm not sure what is happening previously written lines in a multiline command.

### Actual behavior

Just current line is shown.

**Comment by Shougo** [comment] 2022-04-14 10:33
It is the same with https://github.com/hrsh7th/nvim-cmp/issues/889?

**Comment by Shougo** [comment] 2022-04-14 10:40
Reproduced.  But it seems neovim specific problem.  It works on Vim.

**Comment by Shougo** [comment] 2022-04-14 10:50
Reproduced without nvim-cmp.

`nvim --clean`
`set cmdheight=2 laststatus=0`
```
for i in range(4)
  echo 'hello'
```

And switch the terminal window.

**Comment by monkoose** [comment] 2022-04-14 10:52
> Reproduced without nvim-cmp.
> 
> `nvim --clean` `set cmdheight=2 laststatus=0`
> 
> ```
> for i in range(4)
>   echo 'hello'
> ```
> 
> And switch the terminal window.
> 
> It seems command line redraw bug. Please report to upstream.

Not sure if it is the same as with nvim-cmp. Vim behaves the same with your example.

**Comment by Shougo** [comment] 2022-04-14 10:53
Well, I need to find the reason.

**Comment by monkoose** [comment] 2022-04-14 10:53
Question is why nvim-cmp even try to add some autocmd to Cmdline when i don't have `cmp-cmdline` source?

**Comment by Shougo** [comment] 2022-04-14 11:01
`CmdlineEnter` autocmd and `:redraw` causes the problem.

**Comment by monkoose** [comment] 2022-04-14 11:05
And the question also is, why this doesn't happen when `cmdheight=1`?

**Comment by Shougo** [comment] 2022-04-14 11:08
Please test below.  It is bug of neovim.

```vim
set cmdheight=2
autocmd CmdlineChanged * redraw
```

I think it cannot be fixed in nvim-cmp side.  Because `:redraw` is needed.

**Comment by Shougo** [comment] 2022-04-14 11:09
something wrong redraw in Vim.  Oh no.

**Comment by monkoose** [comment] 2022-04-14 11:47
> Please test below. It is bug of neovim.
> 
> ```viml
> set cmdheight=2
> autocmd CmdlineChanged * redraw
> ```
> 
> I think it cannot be fixed in nvim-cmp side. Because `:redraw` is needed.

Isn't this desired behavior on redraw?

**Comment by Shougo** [comment] 2022-04-14 12:23
It is not desired behavior.
Redraw should not change the cmdline.

**Comment by monkoose** [comment] 2022-04-14 12:30
Ok. I see the difference between Vim here. Didn't get whats going on on your screenshot at first.

**Comment by Shougo** [comment] 2022-04-14 12:32
It should be reported both Vim and neovim.

**Comment by Shougo** [comment] 2022-04-17 04:22
I have reported both.

https://github.com/neovim/neovim/issues/18140
https://github.com/vim/vim/issues/10210

**Comment by monkoose** [comment] 2022-04-17 07:38
@Shougo Thanks.

**Comment by Shougo** [comment] 2022-04-20 00:52
Vim's display problem is fixed.  The root problem is `floating window is not updated automatically in command line mode`.

**Comment by Shougo** [comment] 2022-04-22 02:46
I have researched neovim's source code.  And it cannot be fixed.

To update floating window, `redraw screen` is needed.  But it resets the command line.

**Comment by Shougo** [comment] 2022-04-22 03:02
I think the problem is not big.

@hrsh7th What do you think?

**Comment by monkoose** [comment] 2022-04-22 05:26
Sill don't get it.

Why if I don't want nvim-cmp for cmdline, and I didn't install cmp-cmdline, but plugin still injects autocmd for it? Haven't look into source, is it hard to move it into cmp-cmdline itself?

**Comment by Shougo** [comment] 2022-04-23 04:05
Hm.  It seems nvim-cmp's issue.  I think it should be called if users enable cmdline completion.

**Comment by hrsh7th** [comment] 2022-05-01 14:02
I think typical vim plugins will define all autocmd in its `plugin/*.vim` file.
So I think it is not a nvim-cmp's issue.

I can change the timing of autocmd registration but I don't plan it.

**Closed by hrsh7th** 2022-05-01 14:02 UTC
Labels: bug
