### ISSUE TITLE
Menu does not have any color

### ISSUE THREAD

**Issue by mohammad5305** [hrsh7th/nvim-cmp#832] opened 2022-03-10 18:49 UTC
In new update menu does not have any color and I know there is highlight for it but I want cmp use  default of colorscheme
![image](https://user-images.githubusercontent.com/71145952/157733644-fe993f0d-152a-4b28-a451-08d9a2f108bd.png)
![image](https://user-images.githubusercontent.com/71145952/157733848-f1d5ad97-0c3a-49ea-81f3-ff3c981b4f28.png)
and my colorscheme is gruvbox
nvim 0.6

**Comment by hrsh7th** [comment] 2022-03-15 02:32
Could you try with tokyonight colorscheme? I think it is not a nvim-cmp's problem.

**Comment by Johnsiras** [comment] 2022-03-15 11:41
same with some other colorschemes!

**Comment by hrsh7th** [comment] 2022-03-15 11:54
The `I have same problem` is not help us.

Please pit the reproducible steps.

**Comment by mohammad5305** [comment] 2022-03-15 16:52
> Could you try with tokyonight colorscheme? I think it is not a nvim-cmp's problem.


thanks, it working with tokyonight do you have any idea why not working with onedark and gruvbox?

![image](https://user-images.githubusercontent.com/71145952/158429829-05af1d58-6eb2-4345-b887-0617094404c7.png)

**Comment by Shougo** [comment] 2022-03-16 02:39
It seems colorscheme problem.
nvim-cmp use highlights but some colorscheme doesn't support them.

**Comment by hrsh7th** [comment] 2022-03-16 03:10
The coloes should be defined via colorscheme and original problem seems to be solved by changing colorscheme. So I'm closing this for now.

**Closed by hrsh7th** 2022-03-16 03:10 UTC
