### ISSUE TITLE
. (dot) command not working properly with gopls

### ISSUE THREAD

**Issue by itaranto** [hrsh7th/nvim-cmp#707] opened 2022-01-05 20:48 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.1

### Minimal reproducible config

```lua
-- Set completeopt to have a better completion experience
vim.opt.completeopt = 'menuone,noselect'

-- nvim-cmp setup
local has_words_before = function()
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match('%s') == nil
end

local luasnip = require 'luasnip'
local cmp = require('cmp')

cmp.setup {
  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(4),
    ['<C-u>'] = cmp.mapping.scroll_docs(-4),
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    },
    ['<Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      elseif has_words_before() then
        cmp.complete()
      else
        fallback()
      end
    end, { 'i', 's' }),
    ['<S-Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, { 'i', 's' }),
  },
  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body)
    end,
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'nvim_lua' },
    { name = 'luasnip' },
    {
      name = 'buffer',
      option = {
        get_bufnrs = function()
          local bufs = {}
          for _, win in ipairs(vim.api.nvim_list_wins()) do
            bufs[vim.api.nvim_win_get_buf(win)] = true
          end
          return vim.tbl_keys(bufs)
        end
      },
    },
    { name = 'calc' },
    { name = 'path' },
    { name = 'spell' },
  },
  formatting = {
      format = function(entry, vim_item)
        vim_item.menu = ({
          nvim_lsp = '[LSP]',
          buffer = '[Buffer]',
          calc = '[Calc]',
          path = '[Path]',
          spell = '[Spell]',
        })[entry.source.name]
        return vim_item
      end,
  },
}
```

### Description

. (dot) command not working properly with gopls

Example:

https://user-images.githubusercontent.com/11463919/148289315-f35439a4-d991-4e52-88fb-2aec508d753d.mp4

What I did here was:
- `ct)`
- Tab-complete some value.
- Confirm using `<CR>`
- Move to a different function and press `.`

### Steps to reproduce

See description.

### Expected behavior

See description.

### Actual behavior

See description.

**Comment by hrsh7th** [comment] 2022-01-06 03:38
@itaranto Please provide more solid reproduction. I have no your go source file. (I don't mean I want you to provide the your go source file. I just mean you should create minimal reproduction.)

**Comment by itaranto** [comment] 2022-01-06 13:26
> @itaranto Please provide more solid reproduction. I have no your go source file. (I don't mean I want you to provide the your go source file. I just mean you should create minimal reproduction.)

It's reproduced with any Go file actually, the video was using an example for the [Docker SDK ](https://docs.docker.com/engine/api/sdk/examples/)but it doesn't really matter.

Let me try to come up with an example that uses the standard library. I'll post it soon.

**Comment by hrsh7th** [comment] 2022-01-06 14:40
@itaranto BTW, the nvim-cmp (and another completion engine) does not support dot-repeat with `snippet expansion`.
If you mean this, I can't fix and will close this issue.

**Comment by itaranto** [comment] 2022-01-06 15:06
> @itaranto BTW, the nvim-cmp (and another completion engine) does not support dot-repeat with `snippet expansion`. If you mean this, I can't fix and will close this issue.

I'm not sure if a snippet expansion is happening here, let me investigate...

**Comment by hrsh7th** [comment] 2022-01-06 15:37
With nvim-cmp, dot-repeat is only possible with the text that is inserted when you select the text.
Text that is expanded on confirmation cannot be dot-repeat.
In any case, please create and show a small reproduction procedure "what kind of state and how you want it to behave".

_google translated_

**Comment by hrsh7th** [comment] 2022-01-15 11:03
Close this at the moment.

**Closed by hrsh7th** 2022-01-15 11:03 UTC
Labels: bug, can't reproduce

**Comment by DownRangeDevOps** [comment] 2023-11-02 03:57
I came across this issue because for whatever reason `nvim-cmp`, [vim-surround](https://github.com/tpope/vim-surround), and [vim-repeat](https://github.com/tpope/vim-repeat) do not play well together. `nvim-cmp` is too complex for me to quickly understand how it works and where to start looking (thanks for all the hard work @hrsh7th).

Eventually I ran across this awesome gist by @kylechui ([nvim-surround](https://github.com/kylechui/nvim-surround) author) on how to [natively implement dot-repeating](https://gist.github.com/kylechui/a5c1258cd2d86755f97b10fc921315c3). That solved my problem (switching to [nvim-surround](https://github.com/kylechui/nvim-surround), which is rewrite of vim-surround functionality in Lua + a lot more). 

I thought both of those resource might be useful for the next poor soul.

Double thanks to all of you wonderful Neovim plugin authors, after years of my life doing gymnastics in Vimscript I'm happy to not spend a single minute more.
