### ISSUE TITLE
commitCharacters replace completion with "0"

### ISSUE THREAD

**Issue by mcchrish** [hrsh7th/nvim-cmp#109] opened 2021-08-28 22:22 UTC
In TypeScript file, selected an item then pressed "(":

https://user-images.githubusercontent.com/7200153/131232397-193fa1ea-193b-4f6c-8bc7-85ae1ecb581e.mov

**Comment by hrsh7th** [comment] 2021-08-29 04:51
@mcchrish I can't reproduce it. Could you provide your setup?

**Comment by mcchrish** [comment] 2021-08-29 05:25
@hrsh7th my cmp config is basic: https://github.com/mcchrish/dotfiles/blob/master/vim/Library/Preferences/nvim/init.lua#L81-L97

I'm able to track down what "kind" of auto-import is not working. It's working if the auto-import is a variable, while I get the strange behavior if the auto-import is a function.

https://user-images.githubusercontent.com/7200153/131239588-00a9baa3-39d1-4db8-b1fe-438728b17ba4.mov

Here's the test repo: https://github.com/mcchrish/test-cmp-auto-import-1

**Comment by hrsh7th** [comment] 2021-08-29 05:37
@mcchrish Thank you for your repro. But I can't reproduce the issue...(And it seems to not set `commitCharacters` to `cmp3` candidate)

I found `coc.nvim` in your init.lua. I'm worrying it is a cause of the problem (Is it conflicts to this behavior...?)

**Comment by dainiusm07** [comment] 2021-08-29 05:39
Same issue here, but in my case that bug appears even without auto import. Function kind autocomplete selections are broken. Thought that it may be related to autopairs plugin that I'm using, but I guess it is not 🤠

**Comment by hrsh7th** [comment] 2021-08-29 05:40
https://user-images.githubusercontent.com/629908/131239916-c9f6070c-1e27-4af9-b006-0aeac87152e1.mp4

**Comment by hrsh7th** [comment] 2021-08-29 05:45
@dainiusm07 Could you see `0` when confirming the item  of`Function` kind?

**Comment by dainiusm07** [comment] 2021-08-29 05:46
@hrsh7th have you actually selected that cmp3 completion? Because all previous ones got autoimported, but the last with function kind haven't. I don't even need "(" i'm just pressing "Enter" and it replaces text to 0.

**Comment by hrsh7th** [comment] 2021-08-29 05:49
At least, The problem does not occurerd in my setup.
https://user-images.githubusercontent.com/629908/131240143-aec3eda9-0f7a-452f-a7bc-3342f63952b7.mp4


I will test with minimal setup.

**Comment by hrsh7th** [comment] 2021-08-29 05:50
Hm... it does not occur too with minimal setup.

**Comment by hrsh7th** [comment] 2021-08-29 05:55
But I can confirm with `(` on `cmp3` item. So it seems to have a commitCharacters.

**Comment by hrsh7th** [comment] 2021-08-29 06:10
Ah. I found the cause maybe.

You should set the `snippet.expand` option.

```lua
cmp.setup {
    snippet = {
      expand = function(args)
        vim.fn['vsnip#anonymous'](args.body)
      end
    },
}
```

**Comment by mcchrish** [comment] 2021-08-29 06:15
That seems to work. 👍 

The previous instruction does not include installing vsnip. So it seems it's required now?

**Comment by dainiusm07** [comment] 2021-08-29 06:16
Just find out that I need to install "hrsh7th/vim-vsnip" for it to work. :D

**Comment by hrsh7th** [comment] 2021-08-29 06:18
I'm thinking now about the snippet engine is required to avoid some of the trouble 😢

**Comment by dainiusm07** [comment] 2021-08-29 06:20
By the way, before it was not required. Did you make it intentionally?

**Comment by hrsh7th** [comment] 2021-08-29 06:22
Yes. It is intentional. I hope to support no-snippet engine but It is difficult for now. So I've added it to the README.md.

**Comment by dainiusm07** [comment] 2021-08-29 06:27
So issues got resolved. I believe we can close it, right?

**Closed** 2021-08-29 06:29 UTC
Labels: no-info, can't reproduce
