### ISSUE TITLE
Tab keys are broken again

### ISSUE THREAD

**Issue by wookayin** [hrsh7th/nvim-cmp#590] opened 2021-11-29 20:40 UTC
**Describe the bug**

In the command line, `<Tab>` and `<Shift-Tab>` keys are broken since ea10d5b, when cmdline support is not being used but some other plugins for commandline is being used.

![Screenshot](https://user-images.githubusercontent.com/1009873/143938596-f8a0a95c-5611-47e0-ad17-256665b8d1be.gif)

Please see the GIF. FYI I am using wilder.nvim.

1. Press Tab or Shift-Tab to invoke the completion
2. The completion menu does not appear or works as normally when pressing the keys; or weird characters are being inserted.

**To Reproduce**

Config

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'gelguy/wilder.nvim'  " <--------------- NOTE: A new plugin that conflicts
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF


" Wilder.nvim
augroup WilderLazyInit
    autocmd!
    autocmd CmdlineEnter * ++once call s:setup_wilder() | call wilder#main#start()
augroup END

function! s:setup_wilder()
  call wilder#enable_cmdline_enter()
  echom 'setup_wilder called'

  cmap <expr> <Tab>   wilder#in_context() ? wilder#next()     : "\<Tab>"
  cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"

  " renderer: use popupmenu
  let l:wilder_hl = {
        \ 'accent': wilder#make_hl('WilderAccent', 'Pmenu', [
        \     {}, {}, {'foreground': '#f03e3e', 'bold': 1, 'underline': 1}])
        \ }
  let l:wilder_renderer_option = {
        \ 'apply_incsearch_fix': 1,
        \ 'winblend': &pumblend,
        \ 'highlights': l:wilder_hl,
        \ 'reverse': v:false,
        \ 'max_height': '33%',
        \ 'max_width': '90%',
        \ 'left': [' ', wilder#popupmenu_devicons()],
        \ 'right': [' ', wilder#popupmenu_scrollbar()],
        \ }
  call wilder#set_option('renderer', wilder#popupmenu_renderer(l:wilder_renderer_option))


  call wilder#set_option('pipeline', [
        \ wilder#branch(
        \   wilder#cmdline_pipeline({ 'fuzzy' : 2, 'fuzzy_filter': wilder#lua_fzy_filter() }),
        \   wilder#vim_search_pipeline(),
        \ )])
endfunction
```

Related to #436, but it's a different issue. I confirmed that the first commit in which the bug presents is ea10d5b.

**Comment by hrsh7th** [comment] 2021-11-30 01:12
I can't think ea10d5bd2f4ac7653d7a714ab9161d3f52a7a786 causes this problem...

I will investigate. Could you re-bisect this problem?

**Comment by hrsh7th** [comment] 2021-11-30 01:13
I can't get wilder.nvim working by your configuration... I'm also investigating it.

**Comment by hrsh7th** [comment] 2021-11-30 01:30
Please provide the minimum configuration that works properly...

The following configuration is worked fine. I can't reproduce by your config.

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/vim-vsnip'
Plug 'gelguy/wilder.nvim'
call plug#end()
PlugInstall | quit

lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },
  sources = {
    { name = "buffer" },
  },
}
EOF

augroup WilderLazyInit
    autocmd!
    autocmd CmdlineEnter * ++once call s:setup_wilder() | call wilder#main#start()
augroup END

function! s:setup_wilder()
  cmap <expr> <Tab>   wilder#in_context() ? wilder#next()     : "\<Tab>"
  cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"
  call wilder#setup({'modes': [':', '/', '?']})
  call wilder#set_option('renderer', wilder#popupmenu_renderer({
  \   'highlighter': wilder#basic_highlighter(),
  \ }))
endfunction
```

**Comment by wookayin** [comment] 2021-11-30 03:36
> I can't think ea10d5b causes this problem...

I did bisect again and ea10d5b is the first bad commit. Its parent, 9b5d64d works fine. Maybe it was due to an incomplete minimal working configuration, which is somewhat hard to come up with because it happens when other config/plugins exist -- sorry about that. Let me find a minimal rc file again.

**Comment by hrsh7th** [comment] 2021-11-30 03:45
Thank you. Hm...

@wookayin Did you remove the `cmp.setup.cmdline` for transition to the wilder.nvim?

**Comment by wookayin** [comment] 2021-11-30 03:50
Yes, my configuration does not have `cmp.setup.cmdline` nor `cmp.setup { cmdline = ...}` at all.

**Comment by hrsh7th** [comment] 2021-11-30 03:54
@wookayin Can you test with this? https://github.com/hrsh7th/nvim-cmp/issues/590#issuecomment-982195832
I think it should be worked fine in your environment.

**Comment by wookayin** [comment] 2021-11-30 03:59
Yes with that exact configuration Tab/Shift-Tab works OK in both commits (ea10d5b, 9b5d64d). I am very confused what exact line makes my configuration broken.... :|.  I also removed `call wilder#enable_cmdline_enter()` from my config (which was a mistake) but still the same. Still doing the ablation search.

**Comment by hrsh7th** [comment] 2021-11-30 04:27
@wookayin Could you update your `dotfiles` repo? I will look it if updated.

**Comment by hrsh7th** [comment] 2021-12-14 13:08
@wookayin Do you still have this problem?

**Comment by wookayin** [comment] 2021-12-19 04:02
@hrsh7th Yes I still have the problem. I still have difficulties in reproducing a self-contained, minimal vimrc; it would be appreciated if you can try out [my neovim config](https://github.com/wookayin/dotfiles) to reproduce the bug (in a container, an empty machine, etc.).  My config assumes symbolic links `~/.vimrc`, ~/.vim/`, so they may conflict with any existing configurations. If that's bothersome, I will try to make a non-invasive setup for you.

**Comment by wookayin** [comment] 2021-12-26 03:33
@hrsh7th Can you remove `cmap <Tab>` mapping when `cmp.setup.cmdline` is not used?

**Comment by AGou-ops** [comment] 2021-12-30 08:51
@wookayin Hi wookayin,

I used [<Tab/S-Tab> mappings of your config](https://github.com/wookayin/dotfiles/blob/master/nvim/lua/config/lsp.lua#:~:text=%5B%27%3CTab%3E%27%5D%20%3D%20function(fallback,%7D%2C ), and it works, thankx.

I also used `gelguy/wilder.nvim`, and disabled `cmp-cmdline`.

**Comment by wookayin** [comment] 2022-01-05 17:04
@AGou-ops For me, this still does not work. nvim-cmp is agressively overriding `cmap <tab>` **even though** cmp-cmdline is disabled, and I cannot come up with a correct fix or any easy workaround.

**Comment by wookayin** [comment] 2022-01-05 17:17
@hrsh7th Can we remove this autocmd line  (https://github.com/hrsh7th/nvim-cmp/blob/main/plugin/cmp.lua#L23-L24)

```
autocmd CmdlineEnter * call v:lua.cmp.plugin.cmdline.enter()
```

unless cmp-cmdline is used? This doesn't make much sense to me.

**Comment by hrsh7th** [comment] 2022-01-08 05:31
nvim-cmp has a mapping fallback mechanism. Therefore, I don't think the existence of mappings should be the cause of this problem.

Anyway, I don't think plugins should apply mappings automatically. So I'm thinking of a way to remove the default mapping, but that's difficult.

**Comment by hrsh7th** [comment] 2022-01-08 05:32
My previous investigation, the nvim-cmp's mapping fallback mechanism is works fine with wilder.nvim. So I'm interested in why doesn't work in the @wookayin situation.

**Comment by wookayin** [comment] 2022-01-08 10:24
@hrsh7th Thanks for the reply. But I still have some questions:

> nvim-cmp has a mapping fallback mechanism.

I don't understand how fallback works in case cmp **overrides** any existing keymap. In an erroneous situation, there is only one keymap for `<Tab>` in the command mode:

```
:cmap <Tab>
c  <Tab>       * <Cmd>call v:lua.cmp.utils.keymap.set_map(130695748)<CR>
```

But in order for wilder.nvim to correctly work, a custom keymap is needed such as:

```
cmap <expr> <Tab>   wilder#in_context() ? wilder#next()     : "\<Tab>"
```

and upon `CmdlineEnter` nvim-cmp overrides the previous keymap with its own cmap. In this situation, fallback to the previous keymap is impossible. 

What kind of fallback are you talking about? something in a function in `cmp.setup { mapping = ... }` as follows?
```
    ['<Tab>'] = function(fallback)  -- see GH-231, GH-286
      if cmp.visible() then cmp.select_next_item()
      elseif has_words_before() then cmp.complete()
      else fallback() end
    end,
```
This function seems have nothing to do with command line mapping; I traced execution of the function and it is not executed on pressing `<Tab>` **in the command line mode**.

**Comment by hrsh7th** [comment] 2022-01-08 10:32
Could you provide the `cmap` output?
I think `<Plug>(cmp.utils.keymap.evacuate:<Tab>)` will be exists.

**Comment by wookayin** [comment] 2022-01-08 10:34
I see -- it looks like the fallback mechanism is implemented through `<Plug>(cmp.utils.keymap.evacuate:<Tab>)` by backing up any existing keymap.

```
c  <Plug>(cmp.utils.keymap.evacuate:<Tab>)   v:lua.cmp.utils.keymap.set_map(131539691)
c  <Plug>(cmp.utils.keymap.evacuate:<S-Tab>)   v:lua.cmp.utils.keymap.set_map(131539688)
c  <Plug>(cmp.utils.keymap.evacuate:<Up>) * pumvisible() ? "<C-P>" : "<Up>"
c  <Plug>(cmp.utils.keymap.evacuate:<Down>) * pumvisible() ? "<C-N>" : "<Down>"
.... (omitted) ...
c  <Tab>       * <Cmd>call v:lua.cmp.utils.keymap.set_map(131539692)<CR>
.... (omitted) ...
```
But what `v:lua.cmp.utils.keymap.set_map(131539691)` would mean?

**Comment by hrsh7th** [comment] 2022-01-08 10:38
The `v:lua.cmp.utils.keymap.set_map` will invoke the stored mapping function.

```
cmp.setup {
  mapping = {
    ['<Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      else
        fallback()
      end
    end
  }
}
```
The `mapping = { ['<Tab>'] => ...} ` will be `v:lua.cmp.utils.keymap.set_map(...)` and the `fallback` function will be `<Plug>(cmp.utils.keymap.evacuate:...)`

**Comment by hrsh7th** [comment] 2022-01-08 10:55
Oh... but your `<Tab>` fallback key-mapping seems broken. 

```
c  <Plug>(cmp.utils.keymap.evacuate:<Tab>)   v:lua.cmp.utils.keymap.set_map(131539691)
c  <Plug>(cmp.utils.keymap.evacuate:<S-Tab>)   v:lua.cmp.utils.keymap.set_map(131539688)
```
It shouldn't be `v:lua.cmp...`

**Comment by wookayin** [comment] 2022-01-08 11:24
If I trace the execution of `keymap.evacuate(...)`, I see two (previously existing) keymaps of `<Tab>` as follows. Below I write the value of `local map = keymap.get_mapping(mode, lhs)`:

(1) cmap for wilder that I had before
```
{                                          
  buffer = false,                                
  expr = true,                                   
  lhs = "<Tab>",                                 
  noremap = false,                               
  nowait = false,                                
  rhs = 'wilder#in_context() ? wilder#next() ...    
  script = false,                                
  silent = false                                 
}                                                
````

(2) something that I do not recognize
```
{            
  buffer = false,  
  expr = false,    
  lhs = "<Tab>",   
  noremap = true,  
  nowait = false,  
  rhs = "<Tab>",   
  script = false,  
  silent = false   
}                  
```

It looks like the second one (2) causes the wrong fallback (which makes sense as it looks like implementing a recursive keymap). I have no idea why I had something like `noremap <Tab> <Tab>`, probably coming from some plugin rather than vimrc

**Comment by wookayin** [comment] 2022-01-10 15:28
The default keymappings defined in https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/config/default.lua#L60-L111 are causing the problem, and those are getting executed (which I cannot remove). Those keymaps (in the cmdline mode) are mapped from `core.prepare()` calls.

**Comment by wookayin** [comment] 2022-01-10 15:36
Another debugging information: the `fallback()` function inside the cmp keymappings, e.g.,
```
['<Tab>'] = mapping({
  c = function(fallback)
    fallback()
  end
})
```
are those function object in https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/utils/keymap.lua#L103-L105 :
```diff
    callback(
      lhs,
+     misc.once(function()
+       vim.api.nvim_feedkeys(keymap.t(fallback.keys), fallback.mode, true)
+     end)
    )
```
so it will directly feed the keys from the underlying keymap. For example, `<Plug>(cmp.utils.keymap.evacuate:<Tab>)` in my case and this is why I see such weird characters.

However `<Plug>` is used for **internal mapping**, not like normal key sequences. So the fallback/evacuation mechanism is wrong because it will not work with any `<Plug>` mappings.

**Comment by hrsh7th** [comment] 2022-01-10 16:19
Yes. It's called `fallback` in nvim-cmp.

1. nvim-cmp try to map specified keys (e.g. `['<Tab>'] = cmp.mapping.select_next_item()`
2. nvim-cmp detects existing mapping (e.g. `cmap <Tab> wilder#in_context...`
3. nvim-cmp evacuate the existing mapping to another `<Plug>(...evacuate)` mapping
4. If the user press `<Tab>`, nvim-cmp will fallback `<Tab>` via `<Plug>(...evacuate)` for the situation.

**Comment by wookayin** [comment] 2022-01-10 16:31
But I cannot understand why evacuating to the existing mapping is broken as there exist two keymaps for `<Tab>` exist. This seems to be a bug but it was very difficult to trace. I feel that when fallback key mappings are `<expr>`, it breaks.

For example, if I had this configuration (as before)
```vim
  cmap <expr> <Tab>   wilder#in_context() ? wilder#next()     : "\<Tab>"
  cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"
```
the *overridden* keymap will be `c  <Plug>(cmp.utils.keymap.evacuate:<Tab>)  v:lua.cmp.utils.keymap.set_map(325560744)` (which is wrong),

but if I had some two-hop mappings so that the `<Tab>` mapping itself is not a `<expr>` mapping, e.g.,
```vim
  cmap <Tab>   <Plug>(wilder<Tab>)
  cmap <S-Tab> <Plug>(wilder<S-Tab>)
  cmap <expr> <Plug>(wilder<Tab>)   wilder#in_context() ? wilder#next()     : "\<Tab>"
  cmap <expr> <Plug>(wilder<S-Tab>) wilder#in_context() ? wilder#previous() : "\<S-Tab>"
```
there will be **no** evacuation keymaps being registered. I.e., I do not see any `<Plug>(cmp.utils.keymap.evacuate:<Tab>)` in `:cmap`. So this behaves correctly.....................................

This sounds very surprising, but finally I came with a workaround. Do you have any idea why this happens and how you can fix the bug in the right way? Hope this information helps.

**Comment by hrsh7th** [comment] 2022-01-10 16:32
@wookayin Could you test with this branch?
https://github.com/hrsh7th/nvim-cmp/pull/720

**Comment by hrsh7th** [comment] 2022-01-10 16:33
I'm continually improving the keymap handling implementation. I came up with an idea, so I implemented it.

If this problem solved by this branch. I'll merge it.

**Comment by wookayin** [comment] 2022-01-10 16:37
@hrsh7th I tested #720 with my original Tab/S-Tab keymap configs for wilder.nvim (where the main branch remains broken), and **it works** :tada: (with the workaround).  Although with the new implementation I do not see evacuation keymaps but it indeed correctly delegates to the exsiting keymap. Great job!

**Comment by hrsh7th** [comment] 2022-01-10 17:30
Fixed in https://github.com/hrsh7th/nvim-cmp/pull/720

**Comment by wookayin** [comment] 2022-01-10 17:31
Thanks @hrsh7th for implementing #720, which fixes the broken keymaps. I think this can be closed now, but I have
one final question: there no longer exists fallback keymaps being registered, and nvim-cmp's keymap overrides all the keymaps with some black magic <Cmd>call v:lua.cmp.utils.keymap.set_map(...)<CR>. Is there any way to print/retrieve/enumerate underlying keymaps to fallback to?

**Closed by hrsh7th** 2022-01-10 17:30 UTC
Labels: can't reproduce

**Comment by wookayin** [comment] 2022-01-10 18:19
It would be great to add such utility function, because I don't like implicit behaviors that are hard to track/debug. But thanks for the help anyway!
