### ISSUE TITLE
tab completion is intermittently broken

### ISSUE THREAD

**Issue by ExpandingMan** [hrsh7th/nvim-cmp#475] opened 2021-11-04 18:09 UTC
**Describe the bug**
Tab completion is not working (specifically it is inserting a tab instead of selecting a completion option).  Worryingly, the problem is certainly intermittent.  Sometimes when I load up a buffer there is no problem, other times it breaks.  *This is happening even with a minimal config*.

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```lua
vim.o.encoding = "utf-8"

-- no bootstrapping for packer, assumes already installed
Packer = require("packer")
Packer.startup(function()
    -- TEST MODULES HERE
    use "hrsh7th/nvim-cmp"
    use "hrsh7th/cmp-buffer"
    use "hrsh7th/cmp-path"
end)

Cmp = require("cmp")

Cmp.setup({
    sources = {
        {name = "buffer"},
        {name = "path"},
    },
    mapping = {
        ["<tab>"] = Cmp.mapping.select_next_item(),
    }
})
```

**To Reproduce**

1. Creat buffer
2. Enter a line of text, e.g. `alpha`
3. Go to a new line, start typing, buffer completion suggestion shows
4. Press tab.  Sometimes it'll merely insert a tab.

**Expected behavior**
Select next item.

**Additional context**
Think this problem started as of today but am not entirely sure.  It's definitely "recent".

**Comment by ExpandingMan** [comment] 2021-11-04 18:13
I had a way of determining what was the last program to bind a key, but for the life of me I cannot now remember how to do that.

**Comment by gegoune** [comment] 2021-11-04 18:19
Do you mean `:verbose map`?

**Comment by ExpandingMan** [comment] 2021-11-04 18:21
Yes, unfortunately that's useless I guess because of the binding that checks `pumvisible`.

I *think* the bug is caused by the latest commit to `nvim-cmp` but because it's intermittent I can't be completely certain.

**Comment by ExpandingMan** [comment] 2021-11-04 18:23
Yup, I'm almost certain this is caused by the very latest commit.  So far I haven't seen the bug on the next older commit, but I almost always see it on latest.

**Comment by ExpandingMan** [comment] 2021-11-04 18:54
Nope, I also saw it on the next older commit.  This is a very frustrating bug, I can't pin it down and I don't know why it occurs sometimes and not others.  It seems to occur more frequently with my full config but it most definitely still happens with the minimal config.

**Comment by ExpandingMan** [comment] 2021-11-04 19:04
This even happens if I use a custom function for `<tab>`.  I'm extremely stumped.

**Comment by hrsh7th** [comment] 2021-11-05 03:08
@ExpandingMan I guess you are using `copilot.vim`.

The nvim-cmp and copilot.vim both are implemented the `mapping fallback mechanism`.
And please don't use `packet.nvim` for minimal reproduction (it's load the pre-existing plugins automatically)


If so, you should add the following config.
```
  let g:copilot_no_tab_map = v:true
  let g:copilot_assume_mapped = v:true
```

**Comment by ExpandingMan** [comment] 2021-11-05 13:33
I am *not* using `copilot.vim`.  I did not realize that `packer` was silently loading packages, I will explore this some more being more careful to disable other packages.

**Comment by karlc1** [comment] 2021-11-05 15:09
I have this same issue since today. I ran :PackerUpdate for the first time this week at least, and now my cmp tab binding does not work at all. I do not use copilot.

**Comment by karlc1** [comment] 2021-11-05 15:17
Update, I ran :PackerUpdate again since I saw that there were some new commits since a few hours ago. Now my <TAB> binding works, but the <S-TAB> binding does not. Strange

**Comment by ExpandingMan** [comment] 2021-11-05 15:38
I had the same experience, hoping the issue was mysteriously fixed, but of course I started encountering it again a few minutes later (in a new `nvim` session).  I've tried fully disabling some packages (frustrating with packer, exploring the issue [here](https://github.com/wbthomason/packer.nvim/issues/684)) but so far I haven't been able to resolve the issue.

The intermittency of this issue is extremely frustrating.  Debugging of plugins is one of the worst things about neovim in general at the moment, very annoying.

**Comment by mystilleef** [comment] 2021-11-06 09:58
I'm having the same issue. Funnily, when I set `native_menu` to `true`, `tab` begins to work consistently again. @ExpandingMan is this the case for you? I might have to temporarily revert to this until we sort the issue.

**Comment by ExpandingMan** [comment] 2021-11-06 14:50
This seemed to work but a few nvim sessions later, and nope, had the issue again.  Again, it's infuriatingly intermittent so I can never make any certain determinations.

I'm utterly stumped on this but I'm increasingly convinced it's an `nvim-cmp` bug.  I still don't have packer sorted (see [here](https://github.com/wbthomason/packer.nvim/issues/684)) so I'm still not 100% confident I was able to run with 0 plug-ins, but I don't seem to have been able to produce any environment in which this problem does not eventually pop up.

The only way I can think of to finally sort out what is happening here would be to somehow use `verbose` to contextually tell me what is setting the binding for `<tab>`, but this is maddeningly tricky because it has to be sensitive to `pumvisible`.  I've [asked for advice](https://neovim.discourse.group/t/bindings-to-help-with-debugging/1367) on how to do this but it seems that nobody who has read that post knows how to do it either.

When I get more time I'm going to start ripping apart my nvim config to make it more debuggable (though I think nvim absolutely sucks for this no matter what at the moment).

**Comment by mystilleef** [comment] 2021-11-06 15:57
@ExpandingMan  `:imap <tab>` should tell you what is mapped to `tab`

**Comment by ten3roberts** [comment] 2021-11-06 16:46
Running ``imap` <tab` returns "No mapping found", whereas running `imap <c-y>`, which I have mapped to the same custom confirm function returns "i  <C-Y>       * <Cmd>call v:lua.cmp.utils.keymap.set_map(4360414)<CR>", and works as expected, completing, expanding snippets, and moving to the next target.

I am using [paq-nvim](https://github.com/savq/paq-nvim) without any lazy loading or similar.

The setup function is run inside `init.lua`

**Comment by raviqqe** [comment] 2021-11-06 22:20
@ExpandingMan What happens when you try mapping `<Tab>` instead of `<tab>`?

**Comment by ten3roberts** [comment] 2021-11-07 09:45
Yes. `<Tab>` seems to work. I previously used `<TAB>` in the config because `<Tab>` broke a while back, and it was fixed by using `<TAB>`.

Issue solved via workaround

**Comment by mystilleef** [comment] 2021-11-08 06:22
So far so good. Using `<Tab>` instead of `<tab>` works for me too.

**Comment by hrsh7th** [comment] 2021-11-08 11:39
I was self-reviewing the implementations that related to mapping etc.
I've improved the implementations. Could you test with latest main branch?

I can't reproduce it. (`<tab>` and `<Tab>` is already normalized...)

**Comment by ExpandingMan** [comment] 2021-11-08 14:31
> @ExpandingMan :imap <tab> should tell you what is mapped to tab

This doesn't work because I have to be able to execute it when I'm in the middle of typing (because it has to know about `pumvisible`) and I still can't manage to do it.

Latest `main` definitely still has the bug.  I think everyone is being misled into thinking seemingly unrelated changes such as `<Tab>` are affecting it because the problem is so intermittent.

I will have more time to dig into the problem this evening, though at the moment I have no idea what I'll be able to do to get to the bottom of it.

**Comment by ExpandingMan** [comment] 2021-11-08 18:43
Update: after having suffered through this for a while now, I have a bit of confidence that I am seeing a pattern: the bug is much more likely to occur on new buffers.  The good news is that, in practice, I haven't been affected by this bug all that much because I almost never encounter it on existing files.  However, *usually*, but not always, I see it if I create a new buffer and try to use tab-completion.  Hopefully this will be helpful for anyone trying to reproduce it.

**Comment by hrsh7th** [comment] 2021-11-08 18:54
@ExpandingMan What is the result of `:imap` after broken plugin?

**Comment by ExpandingMan** [comment] 2021-11-08 19:01
Ah, I never realized this shows a complete list...  So when tab is *working* I see the line
```
i  <Tab>       * <Cmd>call v:lua.cmp.utils.keymap.set_map(16497821)<CR>
```
but when it's broken I don't see a line for `<tab>` at all.  This still isn't giving me what `verbose` should give me since it doesn't tell me what it was unmapped by.

**Comment by ExpandingMan** [comment] 2021-11-08 23:09
Well, still not really getting anywhere, but I am increasingly sure this is an `nvim-cmp` bug.  I have now tested this with all plugins disabled (and I am sure all plugins were disabled this time) and I still see the issue.  I still don't have a minimal config because of the ongoing packer saga [here](https://github.com/wbthomason/packer.nvim/issues/684), but I have now witnessed the problem with all plugins disabled via my config (which you can find [here](https://gitlab.com/ExpandingMan/neovimconfig)).

The conditions under which this bug appears are still a total mystery to me, other than that it seems far more likely to happen on a fresh buffer.  I have created a small gif showing the intermittency of the issue.  The very last time you see me run `nvim` in this gif, when I insert a `<tab>` I am pressing tab but `nvim-cmp` doesn't do anything.  I made this gif partially to show how similar are the circumstances under which this issue occurs.  Obviously my keystrokes are unlikely to have perfectly consistent timing across the 3 examples, but at least the keys pressed are the same each time.

![cmp-issue](https://user-images.githubusercontent.com/11379353/140832599-12c63fee-096b-4f3e-bf7a-6bf5c1ed3044.gif)

**Comment by hrsh7th** [comment] 2021-11-09 03:00
I guess the bug seems to relate to [this](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/init.lua#L275)

Could you test with moving the https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/init.lua#L277 to https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/init.lua#L285

**Comment by hrsh7th** [comment] 2021-11-09 04:01
Oh...! I'm reproducing it in my local.

**Comment by hrsh7th** [comment] 2021-11-09 05:05
@ExpandingMan I've pushed the experimental improvements for this. Could you test with latest main branch?

**Comment by arpangreat** [comment] 2021-11-09 07:19
> Well, still not really getting anywhere, but I am increasingly sure this is an `nvim-cmp` bug.  I have now tested this with all plugins disabled (and I am sure all plugins were disabled this time) and I still see the issue.  I still don't have a minimal config because of the ongoing packer saga [here](https://github.com/wbthomason/packer.nvim/issues/684), but I have now witnessed the problem with all plugins disabled via my config (which you can find [here](https://gitlab.com/ExpandingMan/neovimconfig)).
> 
> The conditions under which this bug appears are still a total mystery to me, other than that it seems far more likely to happen on a fresh buffer.  I have created a small gif showing the intermittency of the issue.  The very last time you see me run `nvim` in this gif, when I insert a `<tab>` I am pressing tab but `nvim-cmp` doesn't do anything.  I made this gif partially to show how similar are the circumstances under which this issue occurs.  Obviously my keystrokes are unlikely to have perfectly consistent timing across the 3 examples, but at least the keys pressed are the same each time.
> 
> ![cmp-issue](https://user-images.githubusercontent.com/11379353/140832599-12c63fee-096b-4f3e-bf7a-6bf5c1ed3044.gif)
> 

@ExpandingMan there are 2 things I can suggest you :)

- put a `local` before your `Cmp` i.e.
```lua 
local Cmp = require("cmp")
```

- where you are defining your mappings can you do something like this ??

```lua
mapping = {
  ...
  ['<Tab>'] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 's' })
  ...
}
```

**Comment by ExpandingMan** [comment] 2021-11-09 14:54
Still seeing the issue as of latest main, though I haven't tested it without other plugins yet.

> put a local before your Cmp i.e.

Why?  It's not done that way deliberately, this is one of those packages I may want to call from elsewhere.

> where you are defining your mappings can you do something like this ??

Just tried this.  Of course it initially seemed to work because of the usual intermittency, but ultimately no, it does not seem to have changed anything.

**Comment by hrsh7th** [comment] 2021-11-09 17:38
I haven't ever met this problem.

So I try to explain the nvim-cmp's mapping mechanism to help when anyone tries to debug this who can reproduce this.

**1. When nvim-cmp applies the mapping?**
1. https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/init.lua#L274
2. https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/core.lua#L139

**2. How nvim-cmp applies the mapping?**

It's a bit complex.
First, nvim-cmp uses [keymap.listen](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/utils/keymap.lua#L97) to apply the mappings.

The `keymap.listen` will work as the below.

1. Check the keymap has already been applied or not. [here](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/utils/keymap.lua#L102)
2. Save already existing mapping as `<Plug>(cmp.utils.keymap.evacuate:%s)` [here](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/utils/keymap.lua#L177)
3. Apply managed key mapping with fallbacking mechanism [here](https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/utils/keymap.lua#L108)

*2... For example, if you are using `vim-endwise`, that the plugin will apply `<CR>` mapping automatically. But you can still use `nvim-cmp`'s `<Tab>` mapping. Because nvim-cmp will save the existing mapping.


I have no idea for realizing this problem. If someone tries to debug this, hopefully, this explanation will help.

_Sorry. for my poor english._

**Comment by sriramkandukuri** [comment] 2021-11-09 18:03
I have Tab mapping working good, you can refer to My [config](https://github.com/sriramkandukuri/devenv/blob/09ae5a51ca0d2a322ad2ed36055261425b756562/vim/lua/devenv/completions.lua#L126)

**Comment by gegoune** [comment] 2021-11-09 18:10
@hrsh7th Maybe it should be added to documentation? I am pretty sure if you would create initial PR with above some native speakers can review with correct grammar before merging. Feels like implementation details like this could help people a lot.

**Comment by hrsh7th** [comment] 2021-11-09 18:23
I don't think that implementation detailed should be documented.
I will create the vim docs. I think it's enough. (I will do it when the bug report is settled down.

**Comment by ExpandingMan** [comment] 2021-11-09 18:24
Ok... I think it's resolved... because the problem is so hard to pin down, I'm very nervous about ever declaring it is fixed, but since I've made this change I have not encountered the problem despite opening a ton of sessions to try to reproduce it.

I have changed the binding entries in the `mapping` dict to *exactly* reflect what is in the README, in particular
```lua
        ["<Tab>"] = Cmp.mapping.select_next_item({behavior=Cmp.SelectBehavior.Insert}),
        ["<S-Tab>"] = Cmp.mapping.select_prev_item({behavior=Cmp.SelectBehavior.Insert}),
```
If this really has fixed the problem (again, I won't be confident for days) then the issue does not occur if you pass a `behavior` argument to `select_next_item`.  Note that I previously *WAS* seeing the issue with a custom tab function, so it is not the case that the problem only occurs for `select_next_item()`.

@hrsh7th thanks so much for your explanation of what is going on.  If I start to see the issue pop up again, I will use your explanation to dig deeper.  I apologize for not having been able to create a dead-simple MWE.  Intermittent problems are always the worst case scenario for everyone.

And, btw, my determination to keep fiddling with this despite extreme frustration and the existence of countless other vim completion engines is because, in my opinion, this is the very best one.  Most of the others are bloated monstrosities where unexplained issues occur much more often.

**Comment by hrsh7th** [comment] 2021-11-09 18:33
No problem. Rather, I'm sorry to trouble you.
I think the key mapping mechanism of nvim-cmp may be unnecessarily complicated.
but since I'd adopted this design, I think I should take care and fix the bugs relates to this.

_google translated_

BTW, I think `cmp.mapping.select_next_item(...)`'s argument can be omitted by design so it seems the another bug to me...

**Comment by ExpandingMan** [comment] 2021-11-12 17:23
Update: I haven't encountered the issue again since changing my config.  Note that I *have* been keeping `nvim-cmp` up to date, so it's not impossible that an update had something to do with it also.

**Closed** 2021-11-23 11:58 UTC
