### ISSUE TITLE
nvim-cmp probably breaks firenvim in small input boxes

### ISSUE THREAD

**Issue by zim0369** [hrsh7th/nvim-cmp#659] opened 2021-12-20 17:20 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

### Minimal reproducible config

-

### Description

Here is the image for the issue:
https://imgur.com/hvBOryt

Here is the discussion over the issue:
https://github.com/glacambre/firenvim/issues/1271

I then thought it is an issue related to packer:
https://github.com/wbthomason/packer.nvim/issues/738

But they said it is probably caused by to `nvim-cmp`

It only happens with tiny input boxes.

### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

-

**Comment by smjonas** [comment] 2021-12-20 17:52
The error is here https://github.com/hrsh7th/nvim-cmp/blob/9c07c2d1c5581b22f742b891cadd42a311c1cf96/lua/cmp/view/custom_entries_view.lua#L177
and only occurs when entering insert mode at the first line of the buffer.

**Comment by Iron-E** [comment] 2022-01-05 12:33
I believe it is fixed in #472

**Comment by hrsh7th** [comment] 2022-01-15 11:20
I can't reproduce this. I'm installing firenvim and enable it for `input`. But it's works expected.

**Closed by hrsh7th** 2022-01-15 11:20 UTC
Labels: bug
