### ISSUE TITLE
Fix #875 broke funkcionality of gelguy/wilder.nvim (it started to occupy <tab>)

### ISSUE THREAD

**Issue by idevat** [hrsh7th/nvim-cmp#888] opened 2022-04-11 08:46 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

v0.7.0-dev+1395-ge135adcb8

### Minimal reproducible full config

N/A

### Description

After application of commit 3192a0c57837c1ec5bf298e4f3ec984c7d2d60c0 in `nvim-cmp` the plugin `wilder.nvim` stopped to work. It does not react on `<tab>`. It seems that `nvim-cmp` newly takes `<tab>` even if I don't use it in cmdline (i.e. I have not configured it via `cmp.setup.cmdline(':',` because I prefer suggestions in wildmenu).

### Steps to reproduce

N/A

### Expected behavior

`nvim-cmp` don't occupy `<tab>` when is not configured for cmdline.

### Actual behavior

`nvim-cmp` occupy `<tab>` even when it is not configured for cmdline.

**Comment by axieax** [comment] 2022-04-12 03:58
Just wanted to bump https://github.com/hrsh7th/nvim-cmp/issues/875#issuecomment-1094338343 and https://github.com/hrsh7th/nvim-cmp/issues/875#issuecomment-1095313961 which could contain related issues :))

**Comment by jdhao** [comment] 2022-04-12 08:23
I think it is a duplicate of issue https://github.com/hrsh7th/nvim-cmp/issues/880.

**Comment by tzachar** [comment] 2022-04-12 18:19
Why using wilder? almost all (if not all) of the functionality is available in cmp.

**Comment by hrsh7th** [comment] 2022-04-13 15:38
It's fixed now.

**Closed by hrsh7th** 2022-04-13 15:38 UTC
Labels: bug

**Comment by idevat** [comment] 2022-04-14 07:42
@hrsh7th thanks!
@jdhao yes, it looks like duplicate; I'm sorry I missed it
@tzachar wilder allows to use wild menu which I prefer for cmdline completion (it does not hide part of code)

**Comment by tzachar** [comment] 2022-04-14 08:04
@idevat 
Cmp supports wildmenu.
Check this:
https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance
